export const smartfinlyAiFeatureContract = {
  positioning:
    'A goal-based financial planning and investment decision platform for young salaried Indians, helping them budget, protect, invest, and track progress in a personalized but responsible way.',
  audience: [
    'Young middle-class salary earners in India',
    'First-job professionals',
    'Young families balancing EMIs, rent, insurance, tax and goals',
    'Metro, Tier-2 and Tier-3 salary earners',
  ],
  aiRules: [
    'Use structured user profile data as the source of truth.',
    'Explain calculations, assumptions and trade-offs clearly.',
    'Recommend product categories and decision logic, not specific funds, stocks, policies, loans or brokers.',
    'Prioritize emergency fund, debt risk and insurance before risky investment suggestions.',
    'Avoid buy/sell calls, guaranteed returns and regulated-advice language.',
    'Never ask for PAN, Aadhaar, OTP, passwords, bank account numbers, UPI IDs or brokerage credentials.',
  ],
  mvpModules: [
    {
      id: 'profile_builder',
      title: 'User financial profile builder',
      aiRole: 'Summarize income, expenses, liabilities, dependents, risk profile, tax regime and city tier into safe monthly investment capacity.',
      output: 'You can safely invest ₹X/month after emergency fund and debt obligations.',
    },
    {
      id: 'financial_health_score',
      title: 'Financial health score',
      aiRole: 'Score overall readiness using cash flow, emergency fund, debt, insurance, goal progress, tax and risk profile.',
      output: 'Financial Health Score: 72/100 — Good, but emergency fund is weak.',
    },
    {
      id: 'goal_planner',
      title: 'Financial goal planner',
      aiRole: 'Convert target amount, horizon and inflation into required monthly investment and category-level asset direction.',
      output: '₹10 lakh in 5 years may require around ₹14,000–₹15,000/month depending on assumptions.',
    },
    {
      id: 'emergency_fund',
      title: 'Emergency fund calculator',
      aiRole: 'Classify required emergency fund between 3 and 12 months based on job stability, dependents, EMIs and risk.',
      output: 'Build 6–9 months of expenses before increasing risky investments.',
    },
    {
      id: 'sip_planner',
      title: 'SIP and step-up SIP planner',
      aiRole: 'Calculate monthly SIP, step-up SIP, delay impact and salary-increment based SIP increases.',
      output: 'When salary increases by 10%, consider increasing SIP by 5% after checking emergency fund and EMIs.',
    },
    {
      id: 'risk_suitability',
      title: 'Risk profiling and suitability engine',
      aiRole: 'Classify user as beginner conservative, beginner balanced, growth-oriented or advanced using horizon, emergency fund, loans and loss tolerance.',
      output: 'Category-level direction only: FD/RD/liquid/debt, diversified SIPs, index funds, NPS or asset allocation categories.',
    },
    {
      id: 'tax_planning',
      title: 'Tax-saving planner',
      aiRole: 'Explain old vs new regime, 80C, 80D, HRA, NPS and capital-gains/tax-loss concepts educationally.',
      output: 'Compare regimes and show tax context without acting as a tax filer or legal adviser.',
    },
    {
      id: 'progress_dashboard',
      title: 'Progress dashboard',
      aiRole: 'Generate dashboard fields for net worth, savings rate, goal progress, emergency fund, debt, allocation, tax progress, insurance and risk score.',
      output: 'A single dashboard headline plus module-level progress statuses.',
    },
  ],
  mustHaveModules: [
    'Debt and EMI management',
    'Insurance gap analysis',
    'Financial literacy explainers',
    'Behavioural nudges',
    'Goal-based investment category logic',
    'Privacy, consent and trust controls',
  ],
  advancedModules: [
    'Life-stage planning templates',
    'AI financial coach',
    'Scenario simulation',
    'Community benchmarks',
    'India-specific integrations: Account Aggregator, UPI, credit bureau, CAS, EPF, NPS, DigiLocker and income-tax inputs',
  ],
  reportStructure: [
    'Financial Health Score',
    'Safe Monthly Investment Capacity',
    'Emergency Fund Status',
    'Debt and EMI Burden',
    'Insurance Gap',
    'Goal Planner Summary',
    'SIP and Step-up SIP Plan',
    'Tax Planning Summary',
    'Risk Profile and Suitability',
    'Goal-Based Investment Category Direction',
    'Behavioural Nudges',
    'Scenario Simulations',
    'Financial Literacy Explainers',
    'Next 30/60/90 Day Action Plan',
    'Compliance and Assumption Notes',
  ],
}
